### PR TITLE
Fix self-closing tags without attributes or whitespaces

### PR DESCRIPTION
**Pull request by MangelMaxime**
Seems like you don't auto remove trailing space in your code. If this is a problem for you I can update my commit to not clean then.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Nah that's fine for me :smile: Nice catch btw! this bug slipped through. thanks for fix :pray:

**Comment by Zaid-Ajaj** [comment]
Published v1.4, should be available soon, demo page updated too

**Comment by MangelMaxime** [comment]
Thank you :)

I am working on the html-to-elmish project that's why your XML parser is coming at the right time :)

**Comment by Zaid-Ajaj** [comment]
Ohh that sounds interesting! Also a nice way to battle-test the library :smile:

**Pull request merged**
